register:
  number: 1                                  # The account number you want to register
  max_workers: 1                             # Max worker number in multi-threading
  delete_low_balance_account: true           # [IMAP only] Re-register account if the balance is not enough
  delete_low_balance_account_threshold: 60  # [IMAP only] Re-register account balance threshold
  email_server: 
    name: imap_email_server                  # Should be temp_email_server or imap_email_server
    use_custom_address: true                 # [IMAP only] Should be true when use imap_email_server
    custom_email_addresses:                  # 定义多个邮箱账号及其IMAP配置
    - email: another@example.com             # 可以添加邮箱,在云端不建议暴露
      imap_server: imap.example.com
      imap_port: 993
      username: another@example.com
      password: your_app_password
    # - email: another@example.com           # 可以添加更多邮箱
    #   imap_server: imap.example.com
    #   imap_port: 993
    #   username: another@example.com
    #   password: your_app_password


  temp_email_server:                         # Temp email server you use
    name: Gmailpm

  # 保留默认IMAP设置，但实际将使用custom_email_addresses中的配置
  imap_email_server:                         # Default IMAP setting (will be overridden by custom_email_addresses)
    imap_server: imap.example.com
    imap_port: 993
    username: another@example.com
    password: your_app_password


oneapi:
  enabled: false                             # Ingest data into OneAPI server
  url: http://localhost:3000                 # OneAPI server url
  token: your_oneapi_token                   # OneAPI token, see more details in https://github.com/songquanpeng/one-api/blob/main/docs/API.md
  channel_url: http://localhost:3010         # Base url of the channel
  low_balance_threshold: 50                  # Low balance threshold for OneAPI channels cleaning
